### PR TITLE
[WIP] twig gettext extraction

### PR DESCRIPTION
**Pull request by craigh**
refs #8

@cmfcmf @Guite @drak 

I have _NO IDEA_ what I'm doing here. making a stab at it. pretty sure it's missing the final step

### CODE REVIEW

**Comment by cmfcmf** [comment]
This looks wrong. It should only check for Twig Gettext syntax. It should also check in more places.

**Comment by craigh** [comment]
perhaps you missed this part:

> I have NO IDEA what I'm doing here.

:wink: 

feel free to ignore, but we need a fix of some kind!

**Comment by cmfcmf** [comment]
No, I didn't miss it :stuck_out_tongue_closed_eyes: 

I don't have time to fix this myself ATM.

**Comment by craigh** [comment]
ping @drak help please

**Comment by craigh** [comment]
refs #2191 #8 and templates in use here: https://github.com/zikula/core/tree/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Resources/views

**Pull request closed without merging**
